"""Build the 'Import report' deliverable from a committed/staged ImportBatch.

Two shapes:
  * report_data(batch)     -> JSON-serializable dict (used by the API/frontend)
  * report_markdown(batch) -> the human-readable IMPORT_REPORT.md file
"""

from __future__ import annotations

from .models import Anomaly, StagedRow

ACTION_LABELS = {
    StagedRow.Action.CREATE_EXPENSE: "Imported as expense",
    StagedRow.Action.CREATE_SETTLEMENT: "Recorded as settlement",
    StagedRow.Action.MERGE_DUPLICATE: "Dropped as duplicate",
    StagedRow.Action.SKIP: "Skipped",
}


def report_data(batch) -> dict:
    anomalies = list(batch.anomalies.all())
    by_severity = {"error": 0, "warning": 0, "info": 0}
    for a in anomalies:
        by_severity[a.severity] = by_severity.get(a.severity, 0) + 1

    rows = []
    for row in batch.rows.all():
        rows.append({
            "id": row.id,
            "row_number": row.row_number,
            "proposed_action": row.proposed_action,
            "action_label": ACTION_LABELS.get(row.proposed_action, row.proposed_action),
            "status": row.status,
            "raw": row.raw,
            "anomalies": [
                {"code": a.code, "severity": a.severity, "field": a.field,
                 "message": a.message, "action_taken": a.action_taken,
                 "raw_value": a.raw_value, "resolved_value": a.resolved_value}
                for a in row.anomalies.all()
            ],
        })

    return {
        "batch_id": batch.id,
        "filename": batch.filename,
        "status": batch.status,
        "raw_row_count": batch.raw_row_count,
        "anomaly_count": len(anomalies),
        "by_severity": by_severity,
        "rows": rows,
    }


def report_markdown(batch) -> str:
    data = report_data(batch)
    lines = []
    lines.append(f"# Import Report — {data['filename']}")
    lines.append("")
    lines.append(f"- Batch: #{data['batch_id']}  ")
    lines.append(f"- Status: **{data['status']}**  ")
    lines.append(f"- Rows in file: {data['raw_row_count']}  ")
    lines.append(f"- Anomalies detected: **{data['anomaly_count']}** "
                 f"({data['by_severity']['error']} error, "
                 f"{data['by_severity']['warning']} warning, "
                 f"{data['by_severity']['info']} info)")
    lines.append("")
    lines.append("This report is generated by the app every time it ingests the CSV "
                 "(`python manage.py import_csv`). Every row that triggered a data "
                 "problem is listed below with the action the importer took.")
    lines.append("")
    lines.append("| Row | Action | Anomaly | Severity | What happened |")
    lines.append("|----:|--------|---------|----------|---------------|")
    for row in data["rows"]:
        if not row["anomalies"]:
            continue
        for i, a in enumerate(row["anomalies"]):
            action = row["action_label"] if i == 0 else ""
            detail = a["action_taken"].replace("|", "\\|")
            msg = a["message"].replace("|", "\\|")
            lines.append(
                f"| {row['row_number'] if i == 0 else ''} | {action} | "
                f"`{a['code']}` | {a['severity']} | {msg} → _{detail}_ |")
    lines.append("")

    # Summary of clean rows
    clean = [r for r in data["rows"] if not r["anomalies"]]
    lines.append(f"_{len(clean)} row(s) imported with no anomalies._")
    lines.append("")
    return "\n".join(lines)
